project:
  type: website

website:
  title: "Book Sales"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - further-observations.qmd
      - model.qmd

    right:
      - sources.qmd
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true